import {useEffect,useState} from 'react';
import {Orbit as OrbitIcon,Layers3,Rocket,Ruler,ChevronRight,Maximize2,Minimize2,Plus,Minus,RotateCcw,Pause,Play,Rewind,LocateFixed,ArrowUpRight,Radio,Info,X,Navigation as NavIcon} from 'lucide-react';
import UniverseScene,{defaultLayers,type Layers} from '../scene/UniverseScene';
import {catalog,findObject} from '../data/catalog';
import {spacecraftCatalog,missionById} from '../data/spacecraftCatalog';
import {useSimulationClock,MIN_DATE,MAX_DATE} from '../simulation/SimulationClock';
import {dateLabel,distance,duration} from '../utils/format';
import {navigation} from '../navigation/CameraController';
import {positionAt} from '../simulation/positions';
import {levels,scaleLevel,MIN_SPAN,MAX_SPAN} from '../rendering/ScaleManager';
import {loadEphemeris,ephemerisCache} from '../ephemeris/EphemerisCache';
import {fromJD} from '../ephemeris/EphemerisInterpolator';
import {AU,LY,C,norm,subtract} from '../data/constants';
import SceneBoundary from './SceneBoundary';
import Search from './Search';import InfoPanel from './InfoPanel';import MeasurePanel from './MeasurePanel';import MissionTimeline from './MissionTimeline';
const layerLabels: [keyof Layers,string][]=[['orbits','Orbital paths'],['labels','Object labels'],['belts','Asteroid & Kuiper belts'],['heliosphere','Heliosphere'],['oort','Oort Cloud'],['ecliptic','Ecliptic plane'],['planes','Planet orbital planes'],['education','Field notes']];
const notes=[['A world worth coming home to.','The Moon is about 1.3 light-seconds away. Hold Z and see how quickly our home becomes a point.'],['Eight minutes from our star.','The planets are widely separated. In visible-size mode, their radii are enlarged so you can find them.'],['Our farthest footsteps.','Even Voyager has barely started to cross the enormous gulf between stars.'],['The edge of the familiar.','The Oort Cloud is a hypothesized reservoir of icy bodies. Its boundaries remain uncertain.'],['Light takes years to cross this view.','Proxima Centauri is over four light-years away. Voyager is not travelling toward it; this is a comparison of scale.'],['One star among billions.','The Sun lies in the Local Spur, about 26,000 light-years from the Galactic Center.'],['Looking back in time.','Andromeda’s light has travelled for roughly 2.5 million years to reach us.']];
export default function App(){
 const clock=useSimulationClock();const[selected,setSelected]=useState('earth');const[span,setSpan]=useState(45000);const[layers,setLayers]=useState(defaultLayers);const[visibleSize,setVisibleSize]=useState(true);const[quality,setQuality]=useState('High');const[tab,setTab]=useState<'explore'|'missions'|'measure'>('explore');const[immersive,setImmersive]=useState(false);const[category,setCategory]=useState('All missions');const[toast,setToast]=useState('');const[where,setWhere]=useState(false);const[showSources,setShowSources]=useState(false);const[continuous,setContinuous]=useState(false);const[following,setFollowing]=useState(true);const[from,setFrom]=useState('earth');const[to,setTo]=useState('voyager-1');const[pulse,setPulse]=useState<{from:string;to:string;start:number;time:number}|null>(null);const[radioTimes,setRadioTimes]=useState<{arrival:number;reply:number}|null>(null);const[gravity,setGravity]=useState(false);const[compare,setCompare]=useState(false);const[panelOpen,setPanelOpen]=useState(()=>window.innerWidth>760);const[loading,setLoading]=useState(false);
 const body=findObject(selected)??catalog[0];const mission=missionById(selected);const level=scaleLevel(span);
 function notice(s:string){setToast(s)}
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),6500);return()=>clearTimeout(id)},[toast]);
 useEffect(()=>{navigation.zooming=continuous;return()=>{navigation.zooming=false}},[continuous]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest('input,select,textarea'))return;if(e.key==='/'){e.preventDefault();document.querySelector<HTMLInputElement>('[aria-label="Search universe"]')?.focus()}if(e.code==='Space'){e.preventDefault();clock.setPaused(p=>!p)}if(e.key==='Escape'){setContinuous(false);setImmersive(false);setShowSources(false);setWhere(false)}if(e.key.toLowerCase()==='i')setImmersive(i=>!i)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 async function select(id:string){const b=findObject(id);if(!b){notice('This object is not yet available in the catalogue.');return}setSelected(id);setPanelOpen(window.innerWidth>760);setContinuous(false);setGravity(false);setCompare(false);setPulse(null);setRadioTimes(null);if(b.kind==='spacecraft')setCategory('All missions');let time=clock.time;if(b.kind==='spacecraft'){setLoading(true);try{await loadEphemeris(id)}catch{notice('No bundled ephemeris is available for this mission.');setLoading(false);return}setLoading(false);const data=ephemerisCache.get(id)!;if(!positionAt(id,time)){const m=missionById(id)!;time=Math.min(Math.max(time,fromJD(data.samples[0][0])),fromJD(data.samples.at(-1)![0]),m.missionEndDate?Date.parse(m.missionEndDate):Infinity);clock.setTime(time);clock.setPaused(true);notice(`Showing available ephemeris: ${dateLabel(time)}.`)}setLayers(l=>({...l,spacecraft:true}));}const p=positionAt(id,time);if(p){navigation.fly(p,b.focusDistance??Math.max(b.physicalRadius*7,45000),id);setFollowing(true)}}
 function jumpLevel(i:number){setContinuous(false);setGravity(false);setPulse(null);setRadioTimes(null);const l=levels[i];if(i>=4){setSelected(i>=5?'milky-way':'sun');setTab('explore');}if(i===0)setSelected('earth');navigation.fly(positionAt(l.anchor,clock.time)??[0,0,0],l.span,l.anchor);setFollowing(false)}
 function farthest(){setTab('missions');setCategory('Interstellar / escaping');setLayers(l=>({...l,spacecraft:true,trajectories:true,heliosphere:true,belts:true,oort:true}));setSelected('voyager-1');setPulse(null);setRadioTimes(null);navigation.fly([0,0,0],AU*420,'sun');setCompare(true)}
 function focus(){const p=positionAt(selected,clock.time);if(p)navigation.fly(p,body.focusDistance??45000,selected);else notice('This object has no position at the selected date. Choose a mission milestone.');setContinuous(false)}
 function virtualCommand(a='earth',b=selected){const pa=positionAt(a,clock.time),pb=positionAt(b,clock.time);if(!pa||!pb){notice('Positions are unavailable at this date.');return}const seconds=norm(subtract(pa,pb))/C;setPulse({from:a,to:b,start:performance.now(),time:clock.time});setRadioTimes({arrival:clock.time+seconds*1000,reply:clock.time+seconds*2000});setLayers(l=>({...l,communication:true}));navigation.fly(pa.map((v,i)=>(v+pb[i])/2)as [number,number,number],Math.max(norm(subtract(pa,pb))*1.6,1000));notice(`Virtual signal sent · each leg animates in 8 seconds. One-way delay: ${duration(seconds)}.`)}
 function milestone(time:number){setPulse(null);setRadioTimes(null);clock.setTime(Math.min(MAX_DATE,Math.max(MIN_DATE,time)));clock.setPaused(true);const p=positionAt(selected,time);if(p)navigation.fly(p,body.focusDistance??AU*3,selected);else notice('No spacecraft position is bundled for that exact milestone. The timeline event is retained for context.')}
 const v=positionAt('voyager-1',clock.time),earth=positionAt('earth',clock.time)!;const proxima=positionAt('proxima',clock.time);const comparison=v&&proxima?norm(subtract(v,proxima)):null;
 return <main className={immersive?'immersive':''}>
 <SceneBoundary><UniverseScene onSelect={id=>void select(id)} time={clock.time} selected={selected} visibleSize={visibleSize} layers={layers} quality={quality} onScale={setSpan} category={category} pulse={pulse} gravity={gravity}/></SceneBoundary>
 {!immersive&&<><header className="topbar"><a className="brand" href="#" onClick={e=>{e.preventDefault();void select('earth')}}><OrbitIcon size={28} strokeWidth={1.2}/><span>UNIVERSE<span className="brand-light"> EXPLORER</span></span></a><div className="sim-date"><span className="eyebrow">SIMULATION DATE</span><label><input aria-label="Simulation date" type="date" min="1957-01-01" max="2029-12-31" value={new Date(clock.time).toISOString().slice(0,10)} onChange={e=>{if(e.target.value)clock.setTime(Date.parse(e.target.value))}}/><span>UTC</span></label></div><Search onSelect={id=>void select(id)}/><button className="icon-button" aria-label="Immersive mode" title="Immersive mode · I" onClick={()=>setImmersive(true)}><Maximize2 size={18}/></button></header>
 <div className="breadcrumb"><button onClick={()=>jumpLevel(6)}>Universe</button><ChevronRight size={12}/><button onClick={()=>jumpLevel(level)}>{levels[level].name}</button><ChevronRight size={12}/><span>{body.name}</span><button className="address-button" aria-label="Show cosmic address" onClick={()=>setWhere(!where)}><LocateFixed size={12}/>Where are we?</button><span className="view-badge">3D EXPLORATION</span></div>
 <div className="left-panel panel"><div className="tool-tabs"><button aria-label="Explore layers" aria-pressed={tab==='explore'} onClick={()=>setTab('explore')}><Layers3 size={17}/>Explore</button><button aria-label="Browse missions" aria-pressed={tab==='missions'} onClick={()=>setTab('missions')}><Rocket size={17}/>Missions</button><button aria-label="Measure distances" aria-pressed={tab==='measure'} onClick={()=>setTab('measure')}><Ruler size={17}/>Measure</button></div>
 {tab==='explore'?<><div className="section-label">SCENE LAYERS</div>{layerLabels.map(([key,label])=><label className="toggle-row" key={key}><span>{label}</span><input type="checkbox" checked={layers[key]} onChange={e=>setLayers(l=>({...l,[key]:e.target.checked}))}/></label>)}<div className="section-label separated">OBJECT SIZE</div><div className="segmented"><button aria-pressed={!visibleSize} onClick={()=>setVisibleSize(false)}>True size</button><button aria-pressed={visibleSize} onClick={()=>setVisibleSize(true)}>Visible size</button></div><p className="data-note">{visibleSize?'Object radii enlarged for visibility. Distances retain their scale.':'Physical body radii. Spacecraft markers have a separate setting.'}</p><label className="quality-row">Render quality<select value={quality} onChange={e=>setQuality(e.target.value)}>{['Low','Medium','High','Ultra'].map(q=><option key={q}>{q}</option>)}</select></label><button className="where-button" onClick={()=>setWhere(!where)}><LocateFixed size={16}/>Where are we?<ChevronRight size={14}/></button></>:tab==='missions'?<><div className="section-label">SPACECRAFT LAYER</div>{([['spacecraft','Spacecraft'],['trajectories','Spacecraft trajectories'],['missionLabels','Mission labels'],['communication','Communication links'],['spacecraftSize','Exaggerate spacecraft size']] as [keyof Layers,string][]).map(([key,label])=><label key={key} className="toggle-row"><span>{label}</span><input type="checkbox" checked={layers[key]} onChange={e=>setLayers(l=>({...l,[key]:e.target.checked}))}/></label>)}<select aria-label="Mission category" className="category-select" value={category} onChange={e=>setCategory(e.target.value)}>{['All missions','Interstellar / escaping','Outer planets','Inner planets','Solar missions','Asteroids / comets','Historical missions','Active missions','Completed missions'].map(c=><option key={c}>{c}</option>)}</select><div className="mission-list">{spacecraftCatalog.filter(m=>category==='All missions'||category===m.category||category==='Active missions'&&m.communicating||category==='Completed missions'&&!m.communicating||category==='Historical missions'&&!!m.missionEndDate).map(m=><button key={m.id} className={selected===m.id?'active':''} onClick={()=>void select(m.id)}><span style={{color:m.color}}>◇</span>{m.name}<ArrowUpRight size={12}/></button>)}</div><p className="data-note">{layers.spacecraftSize?'Spacecraft size exaggerated for visibility.':''} Lines use cached ephemerides, not live telemetry.</p></>:<MeasurePanel time={clock.time} from={from} to={to} setFrom={setFrom} setTo={setTo} onPulse={()=>virtualCommand(from,to)}/>}
 </div>
 <button className="info-toggle icon-button" aria-label={panelOpen?'Hide object information':'Show object information'} onClick={()=>setPanelOpen(!panelOpen)}><Info size={18}/></button>
 {panelOpen&&<InfoPanel body={body} time={clock.time} onFocus={focus} following={following&&navigation.follow===selected} onFollow={()=>{navigation.follow=navigation.follow===selected?'':selected;setFollowing(navigation.follow===selected)}} onSelect={id=>void select(id)}/>}
 <div className="scene-tools"><button className="icon-button" aria-label="Zoom in" onClick={()=>navigation.zoom(-.6)}><Plus size={18}/></button><button className="icon-button" aria-label="Zoom out" onClick={()=>navigation.zoom(.6)}><Minus size={18}/></button><div/><button className="icon-button" aria-label="Reset camera" onClick={()=>void select('earth')}><RotateCcw size={17}/></button><button className="icon-button" aria-label="Pause camera movement" aria-pressed={navigation.paused} onClick={()=>{navigation.paused=!navigation.paused;setContinuous(false);setSpan(navigation.span)}}><Pause size={16}/></button></div>
 {layers.education&&!mission&&!compare&&<div className="field-note"><div className="eyebrow">FIELD NOTE · 0{level+1}</div><h2>{notes[level][0]}</h2><p>{notes[level][1]}</p></div>}
 {compare&&<div className="comparison panel"><button className="close icon-button" aria-label="Close scale comparison" onClick={()=>setCompare(false)}><X size={14}/></button><div className="eyebrow">VOYAGER · A LITTLE PERSPECTIVE</div><p>Earth → Voyager 1 <b>{v?distance(norm(subtract(v,earth))):'No data at this date'}</b></p><p>Voyager 1 → Proxima <b>{comparison?distance(comparison):'No data at this date'}</b></p><p>Sun–Voyager / Sun–Proxima <b>{v?`${(norm(v)/(4.2465*LY)*100).toFixed(4)}%`:'—'}</b></p><small>A distance comparison. Voyager is not headed toward Proxima.</small><button className="text-button" onClick={()=>jumpLevel(4)}>Zoom to the nearest stars <ArrowUpRight size={14}/></button></div>}
 {mission&&!compare&&<div className="mission-workspace"><MissionTimeline mission={mission} time={clock.time} onDate={milestone}/>{mission.communicating&&<button className="text-button" onClick={()=>virtualCommand()}><Radio size={15}/>Send virtual command</button>}{mission.majorEncounters.some(e=>e.body)&&<button className="text-button" onClick={()=>{setGravity(!gravity);clock.setSpeed(1);clock.setPaused(true)}}>Gravity assist explained <ArrowUpRight size={13}/></button>}{radioTimes&&<p className="data-note">Estimated receive: {new Date(radioTimes.arrival).toLocaleString('en-GB',{timeZone:'UTC'})} UTC · Reply: {new Date(radioTimes.reply).toLocaleString('en-GB',{timeZone:'UTC'})} UTC. Frozen endpoints; immediate reply assumed.</p>}</div>}
 <div className="journey-bar"><button className="journey-feature" onClick={farthest}><Rocket size={15}/><span>Humanity’s farthest</span><ArrowUpRight size={13}/></button><button className={continuous?'zoom-journey active':'zoom-journey'} onClick={()=>setContinuous(!continuous)}><span>{continuous?<Pause size={15}/>:<NavIcon size={15}/>}</span>{continuous?'Pause journey':'Keep going outward'}<kbd>Z</kbd></button><button className="locate-sun" onClick={()=>{void select('sun');setWhere(false)}}><LocateFixed size={14}/>Locate the Sun</button></div>
 <div className="scale-rail"><div className="rail-line"><i style={{width:`${(Math.log(span)-Math.log(MIN_SPAN))/(Math.log(MAX_SPAN)-Math.log(MIN_SPAN))*100}%`}}/></div>{levels.map((l,i)=><button key={l.name} className={level===i?'active':''} onClick={()=>jumpLevel(i)}><span className="rail-dot"/>{l.short}</button>)}</div>
 <footer className="bottom-bar"><div className="scale-readout"><span className="eyebrow">CAMERA DISTANCE</span><strong>{distance(span)}</strong><span className="scale-rule"/></div><div className="time-controls"><button className={clock.reverse?'active icon-button':'icon-button'} aria-label="Reverse time" aria-pressed={clock.reverse} onClick={()=>clock.setReverse(!clock.reverse)}><Rewind size={16}/></button><button className="play-button" aria-label={clock.paused?'Play simulation':'Pause simulation'} onClick={()=>clock.setPaused(!clock.paused)}>{clock.paused?<Play size={17} fill="currentColor"/>:<Pause size={17}/>}</button><select aria-label="Time speed" value={clock.speed} onChange={e=>clock.setSpeed(+e.target.value)}>{[1,10,100,1000,10000,100000,1000000,10000000,100000000,1000000000].map(s=><option key={s} value={s}>{s>=1e9?`${s/1e9}B`:s>=1e6?`${s/1e6}M`:s.toLocaleString()}×</option>)}</select><button className="now-button" onClick={()=>{clock.setTime(Date.now());clock.setReverse(false)}}>Now</button><button className="icon-button" aria-label="Reset simulation" onClick={()=>{clock.setTime(Date.now());clock.setSpeed(1);clock.setPaused(true);clock.setReverse(false)}}><RotateCcw size={14}/></button></div><div className="controls-hint"><span>Drag to orbit · Right-drag to pan</span><button onClick={()=>setShowSources(true)}><Info size={13}/>Data & controls</button></div></footer>
 </>}
 {immersive&&<button className="exit-immersive" onClick={()=>setImmersive(false)}><Minimize2 size={16}/>Exit immersive mode <kbd>I</kbd></button>}
 {where&&<div className="where-popover panel"><button className="close icon-button" aria-label="Close location guide" onClick={()=>setWhere(false)}><X size={15}/></button><div className="eyebrow">OUR COSMIC ADDRESS</div>{['Earth','Solar System','Local Stellar Neighborhood','Orion / Local Spur','Milky Way','Local Group'].map((name,i)=><button key={name} onClick={()=>jumpLevel([0,1,4,5,5,6][i])}><span>0{i+1}</span>{name}<ChevronRight size={13}/></button>)}</div>}
 {gravity&&<div className="gravity-panel panel"><button className="close icon-button" aria-label="Close gravity assist" onClick={()=>setGravity(false)}><X size={15}/></button><div className="eyebrow">GRAVITY ASSIST · SCHEMATIC</div><svg viewBox="0 0 360 145" role="img" aria-label="Spacecraft approach and exit vectors bend around a moving planet"><defs><marker id="arrow" markerWidth="7" markerHeight="7" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="#d5b77e"/></marker></defs><path d="M20 100 Q160 100 176 69 Q210 20 330 25" fill="none" stroke="#d5b77e" strokeWidth="2" markerEnd="url(#arrow)"/><circle cx="184" cy="94" r="17" fill="#7895b3"/><path d="M184 117 L270 117" stroke="#a0bacb" strokeWidth="2" markerEnd="url(#arrow)"/><text x="20" y="83">Approach</text><text x="280" y="54">Exit</text><text x="209" y="138">Planet velocity</text></svg><p>In the Sun’s frame, a spacecraft exchanges momentum with a moving planet. A flyby can increase or decrease its speed and change its direction.</p><small>Vectors are illustrative, not a reconstruction of this encounter.</small></div>}
 {showSources&&<div className="modal-backdrop" onClick={()=>setShowSources(false)}><section role="dialog" aria-modal="true" aria-label="Data and controls" className="modal panel" onClick={e=>e.stopPropagation()}><button className="close icon-button" aria-label="Close data and controls" onClick={()=>setShowSources(false)}><X size={18}/></button><div className="eyebrow">UNIVERSE EXPLORER</div><h2>A map, with honest limits.</h2><p>Planet positions use approximate Keplerian orbits. Moon phases are illustrative. Spacecraft use bundled NASA/JPL Horizons state vectors with interpolation; there is no extrapolation beyond available coverage.</p><p>Solid paths show ephemerides before the simulation date and today. Dashed paths show predictions. Pioneer positions after last contact are predicted. Operational mission status is not a live feed.</p><p>Heliosphere and Oort Cloud boundaries are uncertain. Galactic structure and the background star field are procedural illustrations. Nearby catalogue positions use celestial coordinates.</p><p>Drag: orbit · Right-drag: pan · Wheel: zoom · Hold Z: outward journey · Space: simulation pause · I: immersive · /: search · Esc: close or stop.</p><p>Touch: one finger rotates, two fingers pan. Use + / − to zoom. The selectable scale rail also supports keyboard navigation.</p><div className="source-links"><a href="https://ssd.jpl.nasa.gov/planets/approx_pos.html" target="_blank" rel="noreferrer">JPL planetary elements ↗</a><a href="https://ssd.jpl.nasa.gov/horizons/" target="_blank" rel="noreferrer">NASA/JPL Horizons ↗</a><a href="https://science.nasa.gov/solar-system/" target="_blank" rel="noreferrer">NASA Solar System ↗</a><a href="https://simbad.cds.unistra.fr/simbad/" target="_blank" rel="noreferrer">SIMBAD stellar catalogue ↗</a></div><p className="data-note">Earth / Moon imagery from the Three.js examples. See the project’s DATA_SOURCES.md for provenance and limitations. Works offline from the local server with the bundled datasets.</p></section></div>}
 {loading&&<div className="loading-status" role="status">Loading mission ephemeris…</div>}{toast&&<div className="toast" role="status">{toast}<button aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={14}/></button></div>}
 </main>
}
