import {Crosshair,LocateFixed,ArrowUpRight} from 'lucide-react';
import type {SpaceObject} from '../data/types';
import {missionById} from '../data/spacecraftCatalog';
import {positionAt} from '../simulation/positions';
import {ephemerisCache} from '../ephemeris/EphemerisCache';
import {interpolate,fromJD} from '../ephemeris/EphemerisInterpolator';
import {norm,subtract} from '../data/constants';
import {dateLabel,distance,lightTime} from '../utils/format';
export function Fact({label,value}:{label:string;value:React.ReactNode}){return <div className="fact"><dt>{label}</dt><dd>{value}</dd></div>}
export default function InfoPanel({body,time,onFocus,onFollow,following,onSelect}:{body:SpaceObject;time:number;onFocus:()=>void;onFollow:()=>void;following:boolean;onSelect:(id:string)=>void}){const p=positionAt(body.id,time),earth=positionAt('earth',time)!;const m=missionById(body.id),data=ephemerisCache.get(body.id);const state=data?interpolate(data.samples,time):undefined;const orbitalRadii=data?.samples.filter(s=>s[0]>time/86400000+2440587.5-120&&s[0]<time/86400000+2440587.5+120).map(s=>Math.hypot(s[1],s[2],s[3]));const ended=!!m?.missionEndDate&&time>Date.parse(m.missionEndDate);return <aside className="info-panel panel"><div className="eyebrow"><span style={{background:body.color}} className="type-dot"/>{body.kind==='planet'?'Terrestrial & giant worlds':body.kind==='spacecraft'?'Humanity beyond Earth':body.kind==='galaxy'?'An island of stars':body.kind==='moon'?'Natural satellite':'Celestial object'}</div><h1>{body.name}</h1><div className="object-subtitle">{body.kind==='spacecraft'?m?.agency:body.kind==='planet'?'Solar System':body.kind==='moon'?`Moon of ${body.orbit?.parent}`:body.spectral??body.galaxyType??'Explore the cosmos'}</div><div className="panel-actions"><button className="primary" onClick={onFocus}><Crosshair size={15}/> Focus</button><button className={following?'active':''} onClick={onFollow}><LocateFixed size={15}/>{following?'Following':'Follow'}</button></div><div className="section-label">OVERVIEW</div><p className="description">{body.description}</p>{m&&<p className="status-note">{time<Date.parse(m.launchDate)?'Not yet launched at this date':ended?m.status:m.id.startsWith('pioneer')?m.status:m.missionEndDate?'Historical mission in flight at this simulation date':`${m.status} · operational status is not live telemetry`}</p>}<dl>
 {m?<><Fact label="Launched" value={dateLabel(Date.parse(m.launchDate))}/><Fact label="Region" value={p?norm(p)>120*149597870.7?"Beyond the heliopause scale":"Solar System":"No position at this date"}/><Fact label="From the Sun" value={p?distance(norm(p)):'Outside available coverage'}/><Fact label="From Earth" value={p?distance(norm(subtract(p,earth))):'Unavailable'}/><Fact label="One-way light time" value={p?lightTime(norm(subtract(p,earth))):'Unavailable'}/><Fact label="Heliocentric speed" value={state?`${norm(state.velocity).toFixed(2)} km/s`:'Unavailable'}/>{body.id==='parker'&&orbitalRadii&&orbitalRadii.length>0&&<><Fact label="Perihelion · sampled" value={distance(Math.min(...orbitalRadii))}/><Fact label="Aphelion · sampled" value={distance(Math.max(...orbitalRadii))}/></>}{m.missionEndDate&&<Fact label="Mission ended" value={dateLabel(Date.parse(m.missionEndDate))}/>}</>:body.kind==='galaxy'?<><Fact label="Distance from Sun" value={distance(body.distance??0)}/><Fact label="Diameter · approximate" value={body.diameter??'Uncertain'}/><Fact label="Star population" value={body.population??'Uncertain'}/><Fact label="Group" value={body.group??'—'}/></>:body.kind==='star'&&body.id!=='sun'?<><Fact label="Distance from Sun" value={distance(body.distance??0)}/><Fact label="Spectral type" value={body.spectral??'Uncertain'}/><Fact label="Mass" value={body.mass??'Not included'}/><Fact label="Luminosity" value={body.luminosity??'Not included'}/><Fact label="Planetary system" value={body.planetarySystem??'Not included; see catalogue'}/></>:<><Fact label="Mean radius" value={`${body.physicalRadius.toLocaleString()} km`}/><Fact label="Mass" value={body.mass??'Not included'}/><Fact label="From the Sun" value={p?distance(norm(p)):'—'}/><Fact label="Orbital period" value={body.orbit?`${body.orbit.period.toLocaleString()} days`:'—'}/><Fact label="Rotation period" value={body.rotation?`${Math.abs(body.rotation).toFixed(2)} h${body.rotation<0?' · retrograde':''}`:'—'}/>{body.moons&&<Fact label="Moons" value={body.moons}/>}</>}
 </dl>{data&&<div className="data-note">{m?.finalEvent&&<>Final event: {m.finalEvent}<br/></>}JPL Horizons · cached ephemeris<br/>{dateLabel(fromJD(data.samples[0][0]))} — {dateLabel(fromJD(data.samples.at(-1)![0]))}<br/>Interpolated; predictions are not observations.</div>}{!m&&<div className="data-note">{body.kind==='planet'?'Approximate Keplerian orbit · J2000 elements':body.kind==='moon'?'Representative orbit · phase is illustrative':'Approximate catalogue values; procedural detail is illustrative.'}</div>}{body.id==='saturn'&&<div className="related"><button onClick={()=>onSelect('cassini')}>Cassini <ArrowUpRight size={13}/></button><button onClick={()=>onSelect('huygens')}>Huygens <ArrowUpRight size={13}/></button></div>}{body.id==='jupiter'&&<button className="text-button" onClick={()=>onSelect('juno')}>Explore Juno’s orbit <ArrowUpRight size={13}/></button>}</aside>}
