import {useMemo,useRef} from 'react';
import {useFrame} from '@react-three/fiber';
import {Html} from '@react-three/drei';
import {BufferGeometry,Float32BufferAttribute,Group,PointsMaterial} from 'three';
import {AU} from '../data/constants';
import {navigation} from '../navigation/CameraController';
import {lodFade,rebase} from '../rendering/ScaleManager';
import type {Layers} from './UniverseScene';
export function random(seed=7){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}}
function Dust({inner,outer,count,spherical=false}:{inner:number;outer:number;count:number;spherical?:boolean}){const ref=useRef<Group>(null!),mat=useRef<PointsMaterial>(null!);const geometry=useMemo(()=>{const rng=random(42+inner);const a=[];for(let i=0;i<count;i++){const angle=rng()*Math.PI*2,r=inner+(outer-inner)*rng();if(spherical){const u=2*rng()-1,s=Math.sqrt(1-u*u);a.push(r*s*Math.cos(angle),r*u,r*s*Math.sin(angle))}else a.push(Math.cos(angle)*r,(rng()-.5)*r*.08,Math.sin(angle)*r)}const g=new BufferGeometry();g.setAttribute('position',new Float32BufferAttribute(a,3));return g},[inner,outer,count,spherical]);useFrame(()=>{const n=navigation;ref.current.position.set(...rebase([0,0,0],n.origin,n.span));ref.current.scale.setScalar(AU/n.span*10);const span=n.span/AU;mat.current.opacity=lodFade(span,inner*.25,inner*2)*(1-lodFade(span,outer*6,outer*30))*(spherical?.18:.38);ref.current.visible=mat.current.opacity>.003});return <group ref={ref}><points geometry={geometry}><pointsMaterial ref={mat} color={spherical?'#a2b3d1':'#acaa9e'} size={1} sizeAttenuation={false} transparent depthWrite={false}/></points></group>}
export function Boundary({radius,name,color='#5c8a9c',shell=false}:{radius:number;name:string;color?:string;shell?:boolean}){const ref=useRef<Group>(null!),label=useRef<HTMLSpanElement>(null!);const geometry=useMemo(()=>{const a=[];for(let i=0;i<=192;i++){const t=i/192*Math.PI*2;a.push(Math.cos(t),0,Math.sin(t))}const g=new BufferGeometry();g.setAttribute('position',new Float32BufferAttribute(a,3));return g},[]);useFrame(()=>{const n=navigation;const v=n.span>radius*AU*.2&&n.span<radius*AU*10;ref.current.visible=v;ref.current.position.set(...rebase([0,0,0],n.origin,n.span));ref.current.scale.setScalar(radius*AU/n.span*10);if(label.current)label.current.style.display=v?'block':'none'});return <group ref={ref}><lineLoop geometry={geometry}><lineBasicMaterial color={color} transparent opacity={.25}/></lineLoop>{shell&&<mesh scale={[1, .84,1.18]}><sphereGeometry args={[1,48,24]}/><meshBasicMaterial color={color} wireframe transparent opacity={.025} depthWrite={false}/></mesh>}<Html position={[1,0,0]} zIndexRange={[8,0]}><span className="region-label" ref={label}>{name}</span></Html></group>}
export function OuterSystem({layers,quality}:{layers:Layers;quality:string}){const count=quality==='Low'?1200:quality==='Ultra'?14000:5000;const plane=useRef<Group>(null!);useFrame(()=>{if(plane.current){plane.current.position.set(...rebase([0,0,0],navigation.origin,navigation.span));plane.current.scale.setScalar(AU*150/navigation.span*10);plane.current.visible=navigation.span>AU*.2&&navigation.span<AU*5000}});return <>{layers.spacecraft&&[1,10,100,1000,10000,100000].map(r=><Boundary key={r} radius={r} name={`${r.toLocaleString()} AU`} color="#74694f"/>)}{layers.belts&&<><Dust inner={2.1} outer={3.3} count={count}/><Dust inner={30} outer={50} count={count}/><Boundary radius={50} name="KUIPER BELT · 30–50 AU"/></>}{layers.heliosphere&&<><Boundary radius={90} name="Termination shock · approximate" shell/><Boundary radius={120} name="HELIOPAUSE · variable boundary" shell/><Boundary radius={105} name="Heliosheath"/></>}{layers.oort&&<><Dust inner={2000} outer={100000} count={count*2} spherical/><Boundary radius={2000} name="INNER OORT CLOUD · estimated"/><Boundary radius={100000} name="OUTER OORT CLOUD · estimated"/></>}{layers.ecliptic&&<group ref={plane}><mesh rotation={[-Math.PI/2,0,0]}><circleGeometry args={[1,96]}/><meshBasicMaterial color="#6f95a1" transparent opacity={.045} side={2} depthWrite={false}/></mesh><gridHelper args={[2,20,'#385161','#233845']}/></group>}</>}
