import {useEffect,useMemo,useRef,useState} from 'react';
import {useFrame} from '@react-three/fiber';
import {BufferGeometry,Float32BufferAttribute,Group,Line as ThreeLine,LineBasicMaterial,LineDashedMaterial} from 'three';
import {spacecraftCatalog,type Mission} from '../data/spacecraftCatalog';
import {ephemerisCache,loadEphemeris} from '../ephemeris/EphemerisCache';
import {toJD} from '../ephemeris/EphemerisInterpolator';
import {navigation} from '../navigation/CameraController';
import {AU} from '../data/constants';
import {rebase} from '../rendering/ScaleManager';
import {Body} from './Body';
import type {SceneProps} from './UniverseScene';
export function Trajectory({mission,time}:{mission:Mission;time:number}){const root=useRef<Group>(null!);const data=ephemerisCache.get(mission.id);const lines=useMemo(()=>{if(!data)return null;const past:number[]=[],future:number[]=[];const cut=Math.min(toJD(time),toJD(Date.now()));const lastContact=mission.id==='pioneer-10'?toJD(Date.parse('2003-01-23')):mission.id==='pioneer-11'?toJD(Date.parse('1995-09-30')):Infinity;for(const a of data.samples){const v=[a[1]/AU,a[3]/AU,-a[2]/AU];if(a[0]<=Math.min(cut,lastContact))past.push(...v);else future.push(...v)}if(past.length&&future.length)future.unshift(...past.slice(-3));const make=(a:number[],dashed:boolean)=>{const g=new BufferGeometry();g.setAttribute('position',new Float32BufferAttribute(a,3));const m=dashed?new LineDashedMaterial({color:mission.color,transparent:true,opacity:.24,dashSize:2,gapSize:1}):new LineBasicMaterial({color:mission.color,transparent:true,opacity:.6});const line=new ThreeLine(g,m);line.computeLineDistances();return line};return [make(past,false),make(future,true)]},[data,mission,Math.floor(time/86400000)]);useEffect(()=>()=>{lines?.forEach(l=>{l.geometry.dispose();l.material.dispose()})},[lines]);useFrame(()=>{const n=navigation;root.current.position.set(...rebase([0,0,0],n.origin,n.span));root.current.scale.setScalar(AU/n.span*10);root.current.visible=n.span>AU*.01&&n.span<AU*40000;if(lines){const m=lines[1].material as LineDashedMaterial;m.dashSize=n.span/AU*.008;m.gapSize=m.dashSize*.7;}});return <group ref={root}>{lines?.map((line,i)=><primitive key={i} object={line}/>)}</group>}
export function Spacecraft(p:SceneProps){const[revision,setRevision]=useState(0);useEffect(()=>{let live=true;Promise.allSettled(spacecraftCatalog.map(m=>loadEphemeris(m.id))).then(()=>{if(live)setRevision(r=>r+1)});return()=>{live=false}},[]);const list=spacecraftCatalog.filter(m=>!p.category||p.category==='All missions'||p.category===m.category||p.category==='Active missions'&&m.communicating||p.category==='Completed missions'&&!m.communicating||p.category==='Historical missions'&&!!m.missionEndDate);return <group key={revision}>{list.map(m=><group key={m.id}>{p.layers.trajectories&&<Trajectory mission={m} time={p.time}/>}<Body body={m} {...p} labels={p.layers.missionLabels} spacecraftSize={p.layers.spacecraftSize}/></group>)}</group>}
