import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {OrbitControls,Stars} from '@react-three/drei';
import {Suspense,useEffect,useRef} from 'react';
import {catalog} from '../data/catalog';
import {navigation} from '../navigation/CameraController';
import {positionAt} from '../simulation/positions';
import {Body} from './Body';
import {Orbit} from './Orbit';
import {OuterSystem} from './OuterSystem';
import {Spacecraft} from './Spacecraft';
import {LightTravel} from './LightTravel';
import {Galaxies} from './Galaxies';
import {lodFade} from '../rendering/ScaleManager';
import {PerspectiveCamera} from 'three';
export interface Layers {orbits:boolean;labels:boolean;belts:boolean;heliosphere:boolean;oort:boolean;spacecraft:boolean;trajectories:boolean;missionLabels:boolean;communication:boolean;ecliptic:boolean;planes:boolean;education:boolean;spacecraftSize:boolean}
export const defaultLayers:Layers={orbits:true,labels:true,belts:true,heliosphere:true,oort:true,spacecraft:false,trajectories:true,missionLabels:true,communication:false,ecliptic:false,planes:false,education:true,spacecraftSize:true};
export interface SceneProps {onSelect:(id:string)=>void;time:number;selected:string;visibleSize:boolean;layers:Layers;quality:string;onScale:(span:number)=>void;category?:string;pulse?:{from:string;to:string;start:number;time:number}|null;gravity?:boolean}
function Controller({time,onScale}:{time:number;onScale:(n:number)=>void}){const {camera,gl,size}=useThree();const controls=useRef<any>(null);const elapsed=useRef(0);useEffect(()=>{const wheel=(e:WheelEvent)=>{e.preventDefault();navigation.zoom(e.deltaY*.0018)};const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest('input,select,textarea'))return;if(e.key.toLowerCase()==='z'){navigation.zooming=e.type==='keydown';e.preventDefault();}if(e.key==='Escape'){navigation.zooming=false;navigation.flight=null;}};const blur=()=>{navigation.zooming=false};gl.domElement.addEventListener('wheel',wheel,{passive:false});window.addEventListener('keydown',key);window.addEventListener('keyup',key);window.addEventListener('blur',blur);return()=>{gl.domElement.removeEventListener('wheel',wheel);window.removeEventListener('keydown',key);window.removeEventListener('keyup',key);window.removeEventListener('blur',blur)}},[gl]);useFrame((_,dt)=>{if(!navigation.initialized){navigation.origin=positionAt('earth',time)!;navigation.initialized=true;}navigation.tick(dt,id=>positionAt(id,time));const close=1-lodFade(navigation.span,1e5,1e7);(camera as PerspectiveCamera).setViewOffset(size.width,size.height,size.width<760?-size.width*.13*close:0,70*close,size.width,size.height);const c=controls.current;if(c&&c.target.lengthSq()>1e-10){const delta=c.target.clone();navigation.origin=navigation.origin.map((v,i)=>v+delta.getComponent(i)*navigation.span/10)as [number,number,number];camera.position.sub(delta);c.target.set(0,0,0);navigation.follow='';navigation.flight=null;}elapsed.current+=dt;if(elapsed.current>.12){onScale(navigation.span);elapsed.current=0;}},-1);return <OrbitControls ref={controls} makeDefault enableZoom={false} enableDamping dampingFactor={.08} minDistance={10} maxDistance={10} onStart={()=>{navigation.flight=null}}/>}
function Content(p:SceneProps){return <><color attach="background" args={['#070b12']}/><ambientLight intensity={.38}/><directionalLight position={[8,3,5]} intensity={2.6}/><Stars radius={150} depth={30} count={p.quality==='Low'?800:3000} factor={1.2} fade speed={0}/><Controller time={p.time} onScale={p.onScale}/>{catalog.filter(b=>b.kind!=='spacecraft'&&b.kind!=='galaxy').map(b=><Body key={b.id} body={b} time={p.time} selected={p.selected} onSelect={p.onSelect} visibleSize={p.visibleSize} labels={p.layers.labels}/>) }{p.layers.orbits&&catalog.filter(b=>b.orbit).map(b=><Orbit key={b.id} body={b} time={p.time} planes={p.layers.planes}/>)}<OuterSystem layers={p.layers} quality={p.quality}/>{p.layers.spacecraft&&<Spacecraft {...p}/>}<Galaxies {...p}/>{p.layers.communication&&(p.pulse?<LightTravel from={p.pulse.from} to={p.pulse.to} start={p.pulse.start} time={p.pulse.time}/>:p.selected.startsWith('voyager')||p.selected==='new-horizons'?<LightTravel from="earth" to={p.selected} time={p.time}/>:null)}</>}
export default function UniverseScene(p:SceneProps){return <Canvas camera={{position:[6,3,7.4162],fov:45,near:.001,far:600}} dpr={p.quality==='Low'?1:p.quality==='Ultra'?[1,2]:[1,1.5]} gl={{antialias:p.quality!=='Low',alpha:false}}><Suspense fallback={null}><Content {...p}/></Suspense></Canvas>}
